models:
  - name: int_orders_latest_state
    description: "Orders table with the latest state."
    columns:
      - name: order_id
        description: "Identifier of the order."
        tests:
          - not_null
          - unique

      - name: user_id
        description: "Identifier of the user who placed the order."
        tests:
          - not_null

      - name: created_at
        description: "Timestamp when the order was created."
        tests:
          - not_null

      - name: updated_at
        description: "Timestamp when the order was last updated."
        tests:
          - not_null

      - name: amount
        description: "Monetary amount of the order in the original transaction currency."
        tests:
          - not_null

      - name: currency
        description: "Currency code of the order amount."
        tests:
          - not_null

      - name: esim_package
        description: "Identifier of the eSIM package purchased."

      - name: payment_method
        description: "Payment method used for the transaction (e.g. card, paypal)."

      - name: card_country
        description: "Country associated with the payment card used."

      - name: destination_country
        description: "Country where the eSIM is intended to be used."

      - name: status
        description: "Current status of the order in the source system."
        tests:
          - accepted_values:
              values: ['completed', 'refunded', 'failed']
