version: 2

models:
  - name: stg_orders
    description: "Staged orders with normalized types."
    columns:
      - name: order_id
        description: "Identifier of the order."
        tests:
          - not_null

      - name: user_id
        description: "Identifier of the user who placed the order."
        tests:
          - not_null
          - relationships:
              to: ref('stg_users')
              field: user_id

      - name: created_at
        description: "Timestamp when the order was created."
        tests:
          - not_null

      - name: updated_at
        description: "Timestamp when the order was last updated."
        tests:
          - not_null

      - name: amount
        description: "Monetary amount of the order in the original transaction currency."
        tests:
          - not_null

      - name: currency
        description: "Currency code of the order amount."
        tests:
          - not_null

      - name: esim_package
        description: "Identifier of the eSIM package purchased."

      - name: payment_method
        description: "Payment method used for the transaction (e.g. card, paypal)."

      - name: card_country
        description: "Country associated with the payment card used."

      - name: destination_country
        description: "Country where the eSIM is intended to be used."

      - name: status
        description: "Current status of the order in the source system."
        tests:
          - accepted_values:
              values: ['completed', 'refunded', 'failed']

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - order_id
              - status


  - name: stg_users
    description: "Staged users with normalized types."
    columns:
      - name: user_id
        description: "Unique identifier for a user."
        tests:
          - not_null
          - unique
          
      - name: created_at
        description: "Timestamp when the user account was created."
        tests:
          - not_null

      - name: platform
        description: "Platform where the user registered (e.g. iOS, Android, Web)."

      - name: acquisition_channel
        description: "Marketing channel through which the user was acquired."

      - name: ip_country
        description: "Country inferred from the user's IP address at signup."


  - name: stg_exchange_rates
    description: "Staged exchange rates with normalized currency codes."
    columns:
      - name: currency
        description: "Currency code."
        tests:
          - not_null
          - unique

      - name: usd_rate
        description: "Exchange rate to convert from the given currency to USD."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
