version: 2

sources:
  - name: raw
    description: "Raw data loaded from CSV files provided for the Airalo analytics assignment."
    schema: airalo_raw
    tables:
      - name: users
        description: "Raw users data."
        columns:
          - name: user_id
            tests:
              - not_null
              - unique

      - name: orders
        description: "Raw orders data."
        columns:
          - name: order_id
            tests:
              - not_null

          - name: user_id
            tests:
              - not_null

      - name: exchange_rates
        description: "Raw exchange rates by currency."
        columns:
          - name: currency
            tests:
              - not_null
              
          - name: usd_rate
            tests:
              - not_null